---
name: skkumap
description: A new Flutter project.
publish_to: none
version: 3.0.0+3
environment:
  sdk: "^3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: "^1.1.0"
  html: "^0.15.0"
  cupertino_icons: "^1.0.6"
  url_launcher: "^6.1.12"
  shared_preferences: "^2.0.9"
  get_it: "^7.2.0"
  flutter_launcher_icons: "^0.13.1"
  permission_handler: "^11.0.1"
  get: "^4.6.5"
  intl: "^0.18.1"
  share_plus: "^7.0.2"
  screenshot: "^2.0.0"
  flutter_phone_direct_caller: "^2.1.1"
  firebase_core: "^2.14.0"
  firebase_crashlytics: "^3.3.3"
  flutter_config: "^2.0.2"
  flutter_dotenv: "^5.1.0"
  firebase_analytics: "^10.4.3"
  change_app_package_name: "^1.1.0"
  colorful_safe_area: "^1.0.0"
  shimmer: "^3.0.0"
  firebase_dynamic_links: "^5.3.3"
  logger: "^2.0.2"
  google_mobile_ads: "^3.0.0"
  flutter_local_notifications: "^16.1.0"
  flutter_screenutil: "^5.9.0"
  lottie: "^2.6.0"
  collection: "^1.17.1"
  firebase_messaging: "^14.7.1"
  flutter_datetime_picker: "^1.5.1"
  flutter_naver_map: "^1.0.2"
  flutter_platform_alert: "^0.5.0"
  wolt_modal_sheet: "^0.1.2"
  flutter_localization: "^0.1.14"
  form_field_validator: "^1.1.0"
  geolocator: "^10.1.0"
  geocoding: "^2.1.0"
  dio: "^5.3.3"
  flutter_secure_storage: "^9.0.0"
  easy_loading_button: "^0.3.2"
  loading_animation_widget: "^1.2.0+4"
  local_auth: "^2.1.7"
  animated_check: "^1.0.5"
  flutter_vibrate: "^1.3.0"
  firebase_auth: "^4.11.1"
  xml: "^6.3.0"
  flutter_flip_card: "^0.0.4"
  xml2json: "^6.2.1"
  snapping_sheet: "^3.1.0"
  persistent_bottom_nav_bar: "^5.0.2"
  flutter_popup: "^3.1.8"
  live_activities: "^1.9.0"
  sf_symbols: "^0.2.0"
  awesome_bottom_bar: "^1.2.4"
  buttons_tabbar: "^1.3.8"
  squircle: "^0.0.2"
  flutter_sfsymbols: "^2.0.0"
  webview_flutter: "^4.4.3"
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  chat_bubbles: ^1.5.0

dev_dependencies:
  flutter_lints: "^1.0.0"
  flutter_test:
    sdk: flutter
flutter_launcher_name:
  name: 스꾸버스
dependency_overrides:
  intl: any
  flutter_lints: "^2.0.0"
flutter:
  assets:
    - ".env"
    - assets/
    - assets/applogo/
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/SKKU/
  uses-material-design: true
  fonts:
    - family: ProductBold
      fonts:
        - asset: assets/fonts/Product_Sans_Bold.ttf
    - family: CJKBold
      fonts:
        - asset: assets/fonts/NotoSansCJKkr-Bold.otf
    - family: CJKRegular
      fonts:
        - asset: assets/fonts/NotoSansCJKkr-Regular.otf
    - family: CJKMedium
      fonts:
        - asset: assets/fonts/NotoSansCJKkr-Medium.otf
    - family: toss
      fonts:
        - asset: assets/fonts/TossFaceFontMac.ttf
